version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: d3n@d3n.it
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "12701:80"
  app:
    image: golang:1
    environment:
      DB_HOST: "db"
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-changeme}
      DB_NAME: "postgres"
      DB_PORT: 5432
    volumes:
      - $PWD:/go/src
    entrypoint: sleep infinity
    ports:
      - "12700:12700"
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: cache
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    restart: always
    ports:
      - "8083:8081"