package models

type VPEResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
	Data    []struct {
		VgId                       string      `json:"vg_id"`
		Hsh                        string      `json:"hsh"`
		VgEv                       string      `json:"vg_ev"`
		VgIktato                   string      `json:"vg_iktato"`
		VgVerzio                   string      `json:"vg_verzio"`
		VpeAzonosito               string      `json:"vpe_azonosito"`
		IdNev                      string      `json:"id_nev"`
		SzNev                      string      `json:"sz_nev"`
		SzRovidNev                 string      `json:"sz_rovid_nev"`
		FhVezeteknev               string      `json:"fh_vezeteknev"`
		FhKeresztnev               string      `json:"fh_keresztnev"`
		MegrendeloNev              string      `json:"megrendelo_nev"`
		FhTelefonszam              string      `json:"fh_telefonszam"`
		FhMobilszam                string      `json:"fh_mobilszam"`
		Statusz                    string      `json:"statusz"`
		StatuszSzin                string      `json:"statusz_szin"`
		VgBeerkezesIdeje           string      `json:"vg_beerkezes_ideje"`
		ErvenyessegKezdoDatum      string      `json:"ervenyesseg_kezdo_datum"`
		ErvenyessegVegDatum        string      `json:"ervenyesseg_veg_datum"`
		ErvenyessegKezdoIdo        string      `json:"ervenyesseg_kezdo_ido"`
		ErvenyessegVegIdo          string      `json:"ervenyesseg_veg_ido"`
		ErvenyessegKezdoWots       string      `json:"ervenyesseg_kezdo_wots"`
		ErvenyessegVegWots         string      `json:"ervenyesseg_veg_wots"`
		VgKezdoIdo                 string      `json:"vg_kezdo_ido"`
		VgVegIdo                   string      `json:"vg_veg_ido"`
		SvRovidites                string      `json:"sv_rovidites"`
		StatuszKod                 string      `json:"statusz_kod"`
		VgTipusId                  string      `json:"vg_tipus_id"`
		VgIgenyloSzervezetId       string      `json:"vg_igenylo_szervezet_id"`
		VuNev                      string      `json:"vu_nev"`
		IgenylesTipusNev           string      `json:"igenyles_tipus_nev"`
		VgMegjegyzes               interface{} `json:"vg_megjegyzes"`
		VgTulajdonsagok            string      `json:"vg_tulajdonsagok"`
		VgModositasiOkId           string      `json:"vg_modositasi_ok_id"`
		VgAktiv                    string      `json:"vg_aktiv"`
		VgFelujitasiCelu           string      `json:"vg_felujitasi_celu"`
		VgIdoszakId                string      `json:"vg_idoszak_id"`
		VgVoltVizAllapotban        string      `json:"vg_volt_viz_allapotban"`
		VgCrd                      string      `json:"vg_crd"`
		Rownum                     int         `json:"rownum"`
		Id                         string      `json:"id"`
		VizsgalatIdopont           string      `json:"vizsgalat_idopont"`
		LetrehozasIdopont          string      `json:"letrehozas_idopont"`
		VgBeerkezesIdejeTooltip    string      `json:"vg_beerkezes_ideje_tooltip"`
		SzRovidNevTooltip          string      `json:"sz_rovid_nev_tooltip"`
		Megrendelo                 string      `json:"megrendelo"`
		MegrendeloNevTooltip       string      `json:"megrendelo_nev_tooltip"`
		ErintettSzolgalatiHely     []string    `json:"erintett_szolgalati_hely"`
		ErintettVonal              []string    `json:"erintett_vonal"`
		VuNevTooltip               string      `json:"vu_nev_tooltip"`
		IgenylesTipusNevTooltip    string      `json:"igenyles_tipus_nev_tooltip"`
		ErintettSzolghelyVonal     string      `json:"erintett_szolghely_vonal"`
		IgenylesTipusKorlatozasOka string      `json:"igenyles_tipus_korlatozas_oka"`
		Ervenyesseg                string      `json:"ervenyesseg"`
		Link                       string      `json:"link"`
		ShowCheckbox               bool        `json:"show_checkbox"`
	} `json:"data"`
	Pager struct {
		Max    string `json:"max"`
		Limit  string `json:"limit"`
		Offset string `json:"offset"`
	} `json:"pager"`
}
